### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by louis77** [atom/grammar-selector#28]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [grammar-selector](https://github.com/atom/grammar-selector) package, v0.48.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:432

TypeError: Cannot read property 'length' of undefined
    at TextBuffer.module.exports.TextBuffer.lineLengthForRow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:432:29)
    at TextBuffer.module.exports.TextBuffer.getEndPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:922:38)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:985:21)
    at TextBuffer.module.exports.TextBuffer.clipRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:968:20)
    at TextBuffer.module.exports.TextBuffer.getTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:392:20)
    at TokenizedBuffer.module.exports.TokenizedBuffer.getGrammarSelectionContent (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:186:26)
    at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:135:132)
    at DisplayBuffer.module.exports.DisplayBuffer.setGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:823:35)
    at TextEditor.module.exports.TextEditor.setGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2304:33)
    at GrammarListView.module.exports.GrammarListView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/grammar-selector/lib/grammar-list-view.js:60:21)
```

### Commands

```
     -1:02.7.0 application:new-file (atom-text-editor.editor.is-focused)
     -1:02.2.0 core:paste (atom-text-editor.editor.is-focused)
     -1:01.0 core:undo (atom-text-editor.editor.is-focused)
     -0:50.7.0 core:paste (atom-text-editor.editor.is-focused)
     -0:40.6.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  3x -0:38.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:37.6.0 command-palette:toggle (atom-text-editor.editor.mini.is-focused)
     -0:35.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:35.1.0 xml-formatter:indent (atom-text-editor.editor.mini)
     -0:04.0 grammar-selector:show (atom-text-editor.editor)
  2x -0:02.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
pretty-json, v0.4.1
xml-formatter, v0.9.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi @louis77, can you please share what you were doing when this error occurred?  Thanks!

**Comment by louis77** [comment]
Hi @50Wliu , I had a 15 mb XML file in my clipboard and pasted that into the editor. The XML itself was valid, but probably everything in one line.

**Comment by damieng** [comment]
No further reports and the editor has known issues with very long lines so closing this issue here.
