### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scopeName' of undefined

### ISSUE THREAD

**Issue by 50Wliu** [atom/grammar-selector#39]
[Enter steps to reproduce:]

1. Open grammar selector
2. Type in a grammar that doesn't exist, say `i-dont-exist`
3. <kbd>Enter</kbd>

**Atom**: 1.15.0-dev-4eb3f22 x64
**Electron**: 1.4.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [grammar-selector](https://github.com/atom/grammar-selector) package 0.49.0

### Stack Trace

Uncaught TypeError: Cannot read property 'scopeName' of undefined

```
At C:\Users\user\AppData\Local\Atom x64\app-dev\resources\app.asar\node_modules\grammar-selector\lib\grammar-list-view.js:47

TypeError: Cannot read property 'scopeName' of undefined
    at Object.didConfirmSelection (/app.asar/node_modules/grammar-selector/lib/grammar-list-view.js:47:68)
    at SelectListView.confirmSelection (/app.asar/node_modules/atom-select-list/src/select-list-view.js:246:18)
    at HTMLDivElement.coreConfirm (/app.asar/node_modules/atom-select-list/src/select-list-view.js:65:14)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -1:13 grammar-selector:show (input.hidden-input)
     -1:12.1.0 core:confirm (input.hidden-input)
     -1:10.9.0 editor:consolidate-selections (input.hidden-input)
     -1:10.9.0 core:cancel (input.hidden-input)
     -1:04.1.0 grammar-selector:show (input.hidden-input)
  2x -1:02.7.0 core:backspace (input.hidden-input)
     -1:01.3.0 core:confirm (input.hidden-input)
     -0:59.4.0 grammar-selector:show (input.hidden-input)
     -0:58.6.0 core:confirm (input.hidden-input)
     -0:54.1.0 core:select-all (input.hidden-input)
     -0:53.6.0 core:paste (input.hidden-input)
     -0:51.5.0 editor:log-cursor-scope (input.hidden-input)
     -0:50.4.0 editor:consolidate-selections (input.hidden-input)
     -0:50.4.0 core:cancel (input.hidden-input)
     -0:06.4.0 grammar-selector:show (input.hidden-input)
     -0:04.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-java 1.2.5 
autocomplete-python 1.8.37 
file-icons 2.0.14 
fizzy 0.20.0 
language-batch 0.3.3 
language-latex 1.0.0 
language-pegjs 0.5.0 
language-sourcepawn 0.7.2 
language-test 0.0.1 
latex 0.42.3 
latex-autocomplete 1.0.0 
linter 1.11.21 
linter-coffeelint 1.2.1 
linter-eslint 8.1.0 
linter-js-standard 3.8.0 
linter-stylelint 3.7.0 
MagicPython 1.0.3 
pdf-view 0.54.0 
script 3.14.1 
```

/cc @as-cii

**Comment by Ben3eeE** [comment]
I am able to reproduce if I link `grammar-selector` but not on `1.14.0-beta4`.
