### ISSUE TITLE
Uncaught Error: Pane has been destroyed

### ISSUE THREAD

**Issue by justcLv** [atom/grammar-selector#43]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.10
**Thrown From**: [grammar-selector](https://github.com/atom/grammar-selector) package 0.49.3

### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /usr/share/atom/resources/app.asar/src/pane.js:847

Error: Pane has been destroyed
    at Pane.module.exports.Pane.activate (/app.asar/src/pane.js:847:15)
    at Pane.module.exports.Pane.focus (/app.asar/src/pane.js:252:21)
    at /app.asar/src/pane-element.js:50:23)
    at GrammarListView.cancel (/app.asar/node_modules/grammar-selector/lib/grammar-list-view.js:72:39)
    at Object.didCancelSelection (/app.asar/node_modules/grammar-selector/lib/grammar-list-view.js:51:15)
    at SelectListView.cancelSelection (/app.asar/node_modules/atom-select-list/src/select-list-view.js:303:18)
    at SelectListView.didLoseFocus (/app.asar/node_modules/atom-select-list/src/select-list-view.js:32:12)
    at /app.asar/src/text-editor-element.js:244:21)
    at /app.asar/src/pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.activate (/app.asar/src/pane.js:852:27)
    at PaneContainer.module.exports.PaneContainer.activateNextPane (/app.asar/src/pane-container.js:252:26)
    at Pane.module.exports.Pane.destroyed (/app.asar/src/pane.js:873:24)
    at Pane.module.exports.Model.destroy (/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroy (/app.asar/src/pane.js:866:39)
    at destroyCommitEditor (/packages/git-plus/lib/models/git-commit.coffee:58:42)
    at /packages/git-plus/lib/models/git-commit.coffee:76:5
```

### Commands

```
     -1:25.3.0 core:delete (input.hidden-input)
  9x -1:24.5.0 core:move-down (input.hidden-input)
     -1:21.7.0 editor:select-to-end-of-line (input.hidden-input)
     -1:20.2.0 intentions:highlight (input.hidden-input)
     -1:20.1.0 core:copy (input.hidden-input)
     -1:19.7.0 core:move-right (input.hidden-input)
 11x -1:18.3.0 core:move-up (input.hidden-input)
     -1:16.1.0 intentions:highlight (input.hidden-input)
     -1:16 core:paste (input.hidden-input)
     -1:14.1.0 intentions:highlight (input.hidden-input)
     -1:13.9.0 editor:toggle-line-comments (input.hidden-input)
 14x -1:12.6.0 core:move-left (input.hidden-input)
  2x -1:07.8.0 core:backspace (input.hidden-input)
     -1:04.8.0 intentions:highlight (input.hidden-input)
     -1:04.7.0 core:save (input.hidden-input)
     -0:37.3.0 grammar-selector:show (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
atom-beautify 0.29.23 
auto-detect-indentation 1.3.0 
auto-indent 0.5.0 
autoclose-html 0.23.0 
busy-signal 1.4.1 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
git-control 0.9.0 
git-history 3.3.0 
git-plus 7.8.0 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
intentions 1.1.2 
javascript-snippets 1.2.1 
linter 2.1.4 
linter-csslint 1.3.4 
linter-eslint 8.1.7 
linter-sass-lint 1.7.4 
linter-scss-lint 3.1.0 
linter-stylelint 3.10.0 
linter-ui-default 1.2.4 
local-history 4.0.1 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
open-recent 5.0.0 
scss-snippets 0.6.0 
```

**Comment by 50Wliu** [comment]
`at /packages/git-plus/lib/models/git-commit.coffee:76:5`

It appears that this may be caused by the [git-plus](https://atom.io/packages/git-plus) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
